[package]
name = "hide-my-mess"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
version = "0.1.0"
edition = "2021"

[features]
default = ["gpu"]
gpu = ["tensorflow/tensorflow_gpu"]

[dependencies]
eyre = "0.6"
thiserror = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
tensorflow = "0.17"
clap = { version = "3.0.0-rc.7", features = ["derive"] }
nokhwa = { version = "0.9", features = ["input-v4l"] }
image = "0.23"
v4l = "0.12"

# [dependencies.nokhwa]
# version = "0.9"
# features = ["input-v4l", "input-msmf", "input-avfoundation"]
